version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  user-budget:
    lang: python3-http
    handler: ./user_budget
    image: host.docker.internal:5000/user_budget:1.0
    build_args:
      ADDITIONAL_PACKAGE: "libpq-dev gcc python3-dev musl-dev postgresql-dev"
  avg-budget:
    lang: python3-http
    handler: ./avg_budget
    image: host.docker.internal:5000/avg_budget:1.0
    build_args:
      ADDITIONAL_PACKAGE: "libpq-dev gcc python3-dev musl-dev postgresql-dev"

configuration:
  templates:
    - name: python3-http
      source: https://github.com/openfaas/python-flask-template
  copy:
    - ./common